Models/ErrorViewModel.cs
namespace SchoolManagementD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GroupForCreation.cs
namespace SchoolManagementD.Models
{
    public class GroupForCreation
    {
        public string Name { get; set; }
    }
}

Models/GroupForModification.cs
namespace SchoolManagementD.Models
{
    public class GroupForModification
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/StudentForCreation.cs
using SchoolManagementD.Data;

namespace SchoolManagementD.Models
{
    public class StudentForCreation
    {
        public string Name { get; set; }
        public int GroupId { get; set; }

        public List<Group> Groups { get; set; }
    }
}

Models/StudentForModification.cs
using SchoolManagementD.Data;

namespace SchoolManagementD.Models
{
    public class StudentForModification
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int GroupId { get; set; }
        public int? SelectedGroupId { get; set; }

        public List<Group> Groups { get; set; }
    }
}

Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagementD.Data;
using SchoolManagementD.Models;

namespace SchoolManagementD.Controllers
{
    public class GroupController : Controller
    {
        private readonly ApplicationContext _context;
        
        public GroupController(ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var groups = _context.Groups.ToList();
            return View(groups);
        }

        [HttpGet]
        public IActionResult Create() 
        {
            var model = new GroupForCreation();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(GroupForCreation model)
        {
            var group = new Group
            {
                Name = model.Name
            };

            _context.Groups.Add(group);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var group = _context.Groups.Find(id);

            var model = new GroupForModification
            {
                Id = id,
                Name = group.Name
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GroupForModification model)
        {
            var group = new Group
            {
                Id = model.Id,
                Name = model.Name
            };

            _context.Groups.Update(group);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id) 
        {
            var group = _context.Groups.Find(id);
            _context.Groups.Remove(group);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagementD.Models;
using System.Diagnostics;

namespace SchoolManagementD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolManagementD.Data;
using SchoolManagementD.Models;

namespace SchoolManagementD.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationContext _context;

        public StudentController(ApplicationContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var students = await _context.Students.Include(s => s.Group).ToListAsync();
            return View(students);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new StudentForCreation();
            model.Groups = _context.Groups.ToList();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(StudentForCreation model)
        {
            var student = new Student
            {
                Name = model.Name,
                GroupId = model.GroupId
            };

            _context.Students.Add(student);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var student = _context.Students.Find(id);

            var model = new StudentForModification
            {
                Id = id,
                Name = student.Name,
                Groups = _context.Groups.ToList(),
                SelectedGroupId = student.GroupId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(StudentForModification model)
        {
            var student = new Student
            {
                Id = model.Id,
                Name = model.Name,
                GroupId = model.GroupId
            };

            _context.Students.Update(student);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var student = _context.Students.Find(id);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Views/Group/Create.cshtml
@model SchoolManagementD.Models.GroupForCreation
@{
    ViewData["Title"] = "New Group";
}

<div class="row">
    <div class="col-3">

    </div>
    <div class="col-6">
        <form asp-action="Create">
            <label>Name: </label> <br />
            <input class="form-control" asp-for="Name" type="text" /> <br />

            <button class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="col-3">
    </div>
</div>

Views/Group/Edit.cshtml
@model SchoolManagementD.Models.GroupForModification
@{
    ViewData["Title"] = "Edit Group";
}
<div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
        <form asp-action="Create">
            <label>Name: </label> <br />
            <input class="form-control" asp-for="Name" type="text" /> <br />

            <button class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="col-3">
    </div>
</div>

Views/Group/Index.cshtml
@model List<SchoolManagementD.Data.Group> 
@{
    ViewData["Title"] = "Group List";
}

<table class="table table-hover" width="100%">
    <a class="btn btn-primary" asp-action="Create">Create New</a>
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model)
        {
            <tr>
                <td>@group.Id</td>
                <td>@group.Name</td>
                <td>
                    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@group.Id">Edit</a>
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@group.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolManagementD.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolManagementD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Group" asp-action="Index">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SchoolManagementD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model SchoolManagementD.Models.StudentForCreation
@{
    ViewData["Title"] = "New Student";
}

<form asp-action="Create">
    <div class="row">
        <div class="col-6">
            <label>Name: </label>
            <input class="form-control" asp-for="Name" type="text" />
        </div>
        <div class="col-6">
            <label>Group: </label>
            <select class="form-control" asp-for="GroupId">
                @foreach (var g in Model.Groups)
                {
                    <option value="@g.Id">@g.Name</option>
                }
            </select>
        </div>
    </div>
    
    <button class="btn btn-primary">Submit</button>
</form>

Views/Student/Edit.cshtml
@model SchoolManagementD.Models.StudentForModification
@{
    ViewData["Title"] = "Edit Student";
}

<form asp-action="Edit">
    <div class="row">
        <div class="col-6">
            <label>Name: </label>
            <input class="form-control" asp-for="Name" type="text" />
        </div>
        <div class="col-6">
            <label>Group: </label>
            <select class="form-control" asp-for="GroupId">
                @foreach (var g in Model.Groups)
                {
                    var s = Model.SelectedGroupId == g.Id;
                    <option selected="@s" value="@g.Id">@g.Name</option>
                }
            </select>
        </div>
    </div>

    <button class="btn btn-primary">Submit</button>
</form>

Views/Student/Index.cshtml
@model List<SchoolManagementD.Data.Student>
@{
    ViewData["Title"] = "Student List";
}

<table class="table table-hover" width="100%">
    <a class="btn btn-primary" asp-action="Create">Create New</a>
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Group</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.Id</td>
                <td>@student.Name</td>
                <td>@student.Group?.Name</td>
                <td>
                    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@student.Id">Edit</a>
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@student.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>